cc_library(
    name = "buddy_allocator",
    srcs = ["buddy_allocator.cpp"],
    hdrs = ["buddy_allocator.hpp"],
    copts = ["-std=c++20"],
    visibility = ["//visibility:public"],
    deps = [
        "//container:container",
        "//core:core",
    ],
)
