cc_binary(
    name = "interpreter_example",
    srcs = ["interpreter_example.cpp"],
    copts = [
        "-std=c++20",
        "-march=native",
    ],
    deps = [
        "//container",
        "//core:interpreter",
    ],
)
